---
setup_tower_task: True

var_tower_org_name: "Ansible Demo Organization"
var_tower_org_desc: "Ansible Demo Organization"
var_tower_inventory_name: "Ansible Demo Inventory"
var_tower_inventory_desc: "Ansible Demo inventory"
var_tower_host_name: "localhost"
var_tower_project_name: "ANsible Demo Project"
var_tower_project_url: "https://github.com/jeanphilippelevy/cloud03"
var_tower_team_name: "Ansible Demo Team"
var_tower_team_desc: "Ansible Demo Team"
var_tower_job_name: "Create VM"
var_tower_job_play: "vmw-create-vm.yml"
var_tower_user_name: "ansible-demo-user"
var_tower_user_pass: "ansible-demo-user"
var_tower_user_mail: "ansible-demo-user@ansible.fr"
var_tower_user_first_name: "Ansible"
var_tower_user_last_name: "DEMO-USER"
