---
- name: Remove Job Template
  tower_job_template:
    name: "{{var_tower_job_name}}"
    project: "{{var_tower_project_name}}"
    inventory: "{{var_tower_inventory_name}}"
    playbook: "{{var_tower_job_play}}"
    job_type: "run"
    state: absent
  ignore_errors: yes

- name: Remove Project
  tower_project:
    name: "{{var_tower_project_name}}"
    organization: "{{var_tower_org_name}}"
    state: absent
  ignore_errors: yes

- name: Remove User
  tower_user:
    username: "{{var_tower_user_name}}"
    password: "{{var_tower_user_pass}}"
    email: "{{var_tower_user_mail}}"
    first_name: "{{var_tower_user_first_name}}"
    last_name: "{{var_tower_user_last_name}}"    
    state: absent
  ignore_errors: yes

- name: Remove Organization
  tower_organization:
    name: "{{var_tower_org_name}}"
    description: "{{var_tower_org_desc}}"
    state: absent
