---
- name: Remove organization
  tower_organization:
    name: "{{var_tower_org_name}}"
    description: "{{var_tower_org_desc}}"
    state: absent

- name: Remove project
  tower_project:
    name: "{{var_tower_project_name}}"
    organization: "{{var_tower_org_name}}"
    state: absent